# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gall', '0003_remove_posts_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
